ref 1 สุ่มฟรีไปก่อน  1 ที
จากนั้น ลองกดสุ่ม 500 ถ้าสุ่มไม่ได้ก้ไปสุ่ม 100 จน max หรือถ้าสุ่ม500 ได้ก็ไปสุ่ม 100 ต่อจนหมดในฟังชี่น max





step 
เพิ่มstepใหม่ตามนี้ขั้นตอนหลังจากเจอ checkpoint-gacha4 
#step1
โดยเงือนไขแบบใหม่ ให้มันอ่านcoin ตามฟังชั่น 
เช็ค CHECK_COIN-gacha = 1 ไปcopy มาใช้ จากเช็ค CHECK_COIN = 1 
โดยถ้ามันต่ำกว่า สแกนได้ ต่ำกว่า 600 ให้มันมาสุ่ม loop แต่ถ้ามากว่า 700 ให้มันมากกว่า ให้มันปัดเอาเก็บใน coin 700+ ชื่อไฟล์เดิม
พร้อมสแกนชื่อ+[เลข].dat 

#step2
- โดยขั้นตอนใหม่ให้มันทำงานแบบนี้ 
- สุ่มปกติก็คือ1ครั้ง แล้วรอบ2
- ให้มันหา gacha500 ถ้าเจอให้มัน nocions.bmp ให้มันกด back1รอบแล้ว ถ้าไม่เจอ nocions.bmp ก็ไม่เป็นไร
- แล้วกลับไปวนตามจำที่ customในconfig ตามจำนวนloop 
